### ISSUE TITLE
Error in the backup script

### ISSUE THREAD

**Issue by mvdriel** [Oefenweb/ansible-duply#3]
After a recent provision there is an error in the backup script:

```
--- Start running command BKP at 00:00:04.614 ---
Command line error: Expected 2 args, got 1
Enter 'duplicity --help' for help screen.
00:00:05.398 Task 'BKP' failed with exit code '2'.
--- Finished state FAILED 'code 2' at 00:00:05.398 - Runtime 00:00:00.783 ---
```

**Comment by mvdriel** [comment]
It seems that the "Latest Development Snapshot" of duply is used instead of a stable release.

**Comment by tersmitten** [comment]
That's because the author told me to use that one, because he updates that one on regular basis.

What duplicity version are you using?

**Comment by tersmitten** [comment]
What do you think of an intermediate repository? I asked the author politely to move his code to GitHub - to see the code changes, tag versions, make collaboration easier et cetera - but he doesn't see the need.

**Comment by mvdriel** [comment]
I'm using duplicity 0.7.03, but the error is related to a recent update of duply v1.9.3dev. When using the latest stable release of duply (1.9.2) everything works (see pull request #4 )

@tersmitten An intermediate repo seems to me to be a good workaround. We could then easily add a version parameter to this ansible role.

**Comment by tersmitten** [comment]
Have a look at https://github.com/Oefenweb/duply. 

Are you sure it's not version `1.10dev` that's breaking? I'm using `1.9.3dev` and that version seems to be ok.

**Comment by mvdriel** [comment]
The errors occurs when I use the latest development snapshot. The one used by this role.
The versions of duply are not totally clear to me. When I check the latest development snapshot in the changelog it is 1.10dev, but in the code it is 1.9.3dev.

**Comment by mvdriel** [comment]
@tersmitten Thanks! Although I would prefer a stable release as default. ;)

**Comment by tersmitten** [comment]
I understand, but I was lazy and this is the version we are using in production :-)
